# Generated by Django 6.0.4 on 2026-05-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20260505_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
